name: 🐞 Bug Report
description: Report unexpected behavior with HySkript.
title: "[BUG]"
labels: "needs triage"
type: "Bug"
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the observed behavior
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How do you reproduce this? Please provide as much step-by-step detail as possible.
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen when the reproduce steps are followed?
      placeholder: Tell us what you expected to see!
    validations:
      required: true

  - type: input
    attributes:
      label: HySkript Version
      description: Which version of HySkript are you using?
      placeholder: |
        Ex: "1.0.0"
    validations:
      required: true

  - type: input
    attributes:
      label: Server Version
      description: Which version of the server and Hytale are you using?
      placeholder: |
        Ex: "2026-1-18"
    validations:
      required: true

  - type: textarea
    attributes:
      label: HySkript Info
      description: Run '/skript info' and paste here!
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: Any additional information that may help us solve the bug.
      placeholder: |
        Ex: "Using a custom Hytale server build"
    validations:
      required: false
